### ISSUE TITLE
how to use v-annotator package

### ISSUE THREAD

**Issue by ping40** [doccano/v-annotator#10]
source code in [stackblitz](https://stackblitz.com/edit/github-pacaew-kggc5u?file=package.json,app.vue)

from a new Nuxt  project, I run :

`npm install v-annotator`

and modify app.vue, as following: 

```
<template>
  <div>
    <NuxtWelcome />
    test 1234
  </div>
  <v-annotator text="test for annotation" />
</template>

<script lang="ts">
import VAnnotator from 'v-annotator';

export default Vue.extend({
  components: {
    VAnnotator,
  },
});
</script>
```

I got following error:

![500 error](https://github.com/doccano/v-annotator/assets/13582248/c6a6059f-c19d-477c-8dac-b3a27d75317c)

what's wrong with me ?
any suggest is appreciated, thank you .

**Comment by ping40** [comment]
I use vue3, but v-annotator bases on vue 2.

**Comment by qinglongheu** [comment]
> I use vue3, but v-annotator bases on vue 2.

do you know how to use it?
