### ISSUE TITLE
How do I incorporate v-annotator into doccano?

### ISSUE THREAD

**Issue by I-Vostok-I** [doccano/v-annotator#3]
Hello.

I've been working on a version of doccano that utilises a new label type, and so I have modified the v-annotator component as well. However, I am not entirely sure how to get from the v-annotator source code to a built package that can be imported by doccano (in place of v-annotator@0.1.28)

I've tried yarn pack, and then tried adding the .tgz file to doccano's dependencies, and while yarn recognises the package, Vue and the entity-editor do not. I suspect this is because the 'dist' directory for v-annotator differs between what doccano natively imports, and the dist folder generated by yarn pack (or yarn build for that matter) in the v-annotator project.

Excuse the different OSs, but on the left is the contents of the custom-build v-annotator component, while on the right is the default v-annotator component:
![image](https://github.com/doccano/v-annotator/assets/131434448/cc86555f-1253-4c76-921d-072c7870ebaf)

**Comment by I-Vostok-I** [comment]
Issue has been solved. I needed to call yarn bundle-build before calling yarn pack.

**Comment by dimidd** [comment]
Hi, I use a custom v-annotator as well. Could you please elaborate on your setup, e.g. share your frontend Dockerfile(or relevant parts)?
