### ISSUE TITLE
Make maxLabelLength a Vue prop

### ISSUE THREAD

**Issue by nikoferraz** [doccano/v-annotator#4]
Right now there doesn't seem to be any way to change the maxLabelLength property, other than by going to the NPM module itself. Would it be possible to make this a prop so that we can pass a custom value?

**Comment by Hironsan** [comment]
Yes.

1. Add `maxLabelLength` to `VAnnotator` props.
2. Change [valueOf](https://github.com/doccano/v-annotator/blob/c757441bcbf023c75780b0c92e7d0547ce6dd667/src/domain/models/Label/Label.ts#L75) method to pass `maxLabelLength`.
3. Pass `maxLabelLength` to `LabelList.valueOf` in the `VAnnotator` component.

**Comment by nikoferraz** [comment]
Thanks! It looks like it's working now. I submitted a PR related to this issue.
