### ISSUE TITLE
Non-unique element IDs when using several VAnnotators on same page

### ISSUE THREAD

**Issue by saeub** [doccano/v-annotator#6]
Calculation of the BaseEntities' `margin` props relies on the bounding rect of an element with hard-coded ID `container` (see [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VAnnotator.vue#L268)). When there are multiple VAnnotator components on the same page, there will be several elements with ID `container`, and the position of the entities will be incorrectly calculated.

Looking through the code, I also noticed other places with similar problems [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VAnnotator.vue#L150-L152) and [here](https://github.com/doccano/v-annotator/blob/fd31fbb8ff9d42340df48dcd2adeb196083005d2/src/components/VLine.vue#L218-L223).

My idea for fixing this would be to generate a random ID for each VAnnotator component and append it to the IDs of the elements (e.g. `container-7490b8b5-d8f3-4106-8377-fce9f9fb6879`, `text-7490b8b5-d8f3-4106-8377-fce9f9fb6879` etc.). @Hironsan: if you agree with this approach, I'm happy to open a PR.

Or would you prefer a solution using [template refs](https://vuejs.org/guide/essentials/template-refs.html)?

**Comment by Hironsan** [comment]
It looks good. Please open a PR.
