### ISSUE TITLE
can not resolve '.v-annotator'

### ISSUE THREAD

**Issue by wangfpp** [doccano/v-annotator#8]
# code 
Vue@2.X
 "v-annotator": "^0.1.29"
```
import VAnnotator from 'v-annotator'
```
 Can't resolve 'v-annotator'

**Comment by nikoferraz** [comment]
There are several files missing from the dist folder since 0.1.29, including v-annotator.common.js. I think that's the real reason for the error. Although I'm not sure what would've caused this. Could it be that something went amiss during the `yarn publish` step?

**Comment by Hironsan** [comment]
You are right. I just published the new version (0.1.31). Please check it.

- https://www.npmjs.com/package/v-annotator
